[package]
name = "ocipack-rs"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "debuginfo"

[dependencies]
reqwest = { version = "0.11", features = ["gzip", "blocking", "json", "deflate"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
log = "0.4"
env_logger = "0.9"
bytes = "1.1"
sha2 = "0.10"
hex-literal = "0.3"
hex = "0.4"
regex = "1.5"
tar = "0.4"
flate2 = "1.0"
rand = "0.8"
url = "2.2"
home = "0.5"
base64 = "0.13"
clap = { version = "3.2.5", features = ["derive"] }
dockerfile-parser = "0.8.0"
derive_builder = "0.11"
zstd = "0.11"
fantasy-util = "0.1.8"