[package]
name = "ocipack-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["gzip", "blocking", "json", "deflate"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
log = "0.4"
bytes = "1.1"
sha2 = "0.9.8"
hex-literal = "0.3.3"
hex = "0.4.3"
